<?php

namespace EleveBundle\Repository;

/**
 * AffectationTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
