<?php

namespace EleveBundle\Repository;

/**
 * HistoriqueTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
