<?php

namespace EleveBundle\Repository;

/**
 * QuestionnaireSatisfactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireSatisfactionRepository extends \Doctrine\ORM\EntityRepository
{
}
