<?php

namespace EleveBundle\Repository\EntityMain;

/**
 * CourriertypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourriertypeRepository extends \Doctrine\ORM\EntityRepository
{
}
