<?php

namespace EleveBundle\Repository\EntityMain;

/**
 * CourrieretatlectureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourrieretatlectureRepository extends \Doctrine\ORM\EntityRepository
{
}
