<?php

namespace EleveBundle\Repository\EntityMain;

/**
 * FormationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationsRepository extends \Doctrine\ORM\EntityRepository
{
}
