eleve:
    resource: "@EleveBundle/Controller/"
    type:     annotation
    prefix:   /

kms_froala_editor:
    resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
    prefix:   /froalaeditor
    