# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
    session_fixation_strategy: invalidate
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
#        in_memory:
#            memory:
#                users:
#                    admin:
#                        password: cu0707_TMSC
#                        roles: 'ROLE_ADMINISTRATEUR'
    role_hierarchy:
        ROLE_ADMINISTRATEUR: 
            - ROLE_ELEVE
            - ROLE_ASSISTANTE
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_ASSISTANTE: 
            - ROLE_ELEVE
        ROLE_ELEVE: 
            - ROLE_ELEVE
    firewalls:
        main:
            pattern: ^/
            form_login:
                require_previous_session: false
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login 
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                invalidate_session: true
                delete_cookies:
                    name:
                        path:                 null
                        domain:               null
            switch_user: { role: ROLE_ADMINISTRATEUR, parameter: _emprunt_identite }
            anonymous:    true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }