# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        EleveBundle\Entity\EntityCulture\Eleve: 
            id: integer_encoder
        Symfony\Component\Security\Core\User\User:  plaintext
    providers:
        chain_provider:
            chain:
                providers: [in_memory, main]
        main:
            entity: { class: EleveBundle\Entity\EntityCulture\Eleve, property: username }
        in_memory:
            memory:
                users:
                    admin:
                        password: cu0707_TMSC
                        roles: 'ROLE_ADMINISTRATEUR'
    role_hierarchy:
        ROLE_ADMINISTRATEUR: 
            - ROLE_ELEVE
            - ROLE_ASSISTANTE
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_ASSISTANTE: 
            - ROLE_ELEVE
        ROLE_ELEVE: 
            - ROLE_ELEVE
    firewalls:
        main:
            pattern: ^/
            guard:
                authenticators:
                    - app.form_login_authenticator
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: /logout
                target: /
            switch_user: { role: ROLE_ADMINISTRATEUR, parameter: _emprunt_identite }
            anonymous:    true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_ELEVE }