<?php

namespace Proxies\__CG__\EleveBundle\Entity\EntityMain;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Courriertype extends \EleveBundle\Entity\EntityMain\Courriertype implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'service', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'id', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'description', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'cheminFichierContenu', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'datecreation', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'etat', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'titre', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'cheminFichierMail', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'contenuSms', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'cheminFichierNotification', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'objetMail', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'envoiMail', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'envoiNotification', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'envoiSms', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'genererPdf', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'ajoutContactsEleves', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'codeContactEleves', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'contenuHtmlCourrier', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'contenuHtmlMail', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'dispoALaDemande', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'tampon', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'codecourriertype'];
        }

        return ['__isInitialized__', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'service', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'id', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'description', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'cheminFichierContenu', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'datecreation', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'etat', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'titre', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'cheminFichierMail', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'contenuSms', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'cheminFichierNotification', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'objetMail', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'envoiMail', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'envoiNotification', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'envoiSms', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'genererPdf', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'ajoutContactsEleves', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'codeContactEleves', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'contenuHtmlCourrier', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'contenuHtmlMail', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'dispoALaDemande', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'tampon', '' . "\0" . 'EleveBundle\\Entity\\EntityMain\\Courriertype' . "\0" . 'codecourriertype'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Courriertype $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setService($service)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setService', [$service]);

        return parent::setService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', []);

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheminFichierContenu($cheminFichierContenu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheminFichierContenu', [$cheminFichierContenu]);

        return parent::setCheminFichierContenu($cheminFichierContenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheminFichierContenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheminFichierContenu', []);

        return parent::getCheminFichierContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', [$datecreation]);

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', []);

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheminFichierMail($cheminFichierMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheminFichierMail', [$cheminFichierMail]);

        return parent::setCheminFichierMail($cheminFichierMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheminFichierMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheminFichierMail', []);

        return parent::getCheminFichierMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenuSms($contenuSms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenuSms', [$contenuSms]);

        return parent::setContenuSms($contenuSms);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenuSms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenuSms', []);

        return parent::getContenuSms();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheminFichierNotification($cheminFichierNotification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheminFichierNotification', [$cheminFichierNotification]);

        return parent::setCheminFichierNotification($cheminFichierNotification);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheminFichierNotification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheminFichierNotification', []);

        return parent::getCheminFichierNotification();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjetMail($objetMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjetMail', [$objetMail]);

        return parent::setObjetMail($objetMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetMail', []);

        return parent::getObjetMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvoiMail($envoiMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvoiMail', [$envoiMail]);

        return parent::setEnvoiMail($envoiMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvoiMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvoiMail', []);

        return parent::getEnvoiMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvoiNotification($envoiNotification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvoiNotification', [$envoiNotification]);

        return parent::setEnvoiNotification($envoiNotification);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvoiNotification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvoiNotification', []);

        return parent::getEnvoiNotification();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvoiSms($envoiSms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvoiSms', [$envoiSms]);

        return parent::setEnvoiSms($envoiSms);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvoiSms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvoiSms', []);

        return parent::getEnvoiSms();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenererPdf($genererPdf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenererPdf', [$genererPdf]);

        return parent::setGenererPdf($genererPdf);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenererPdf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenererPdf', []);

        return parent::getGenererPdf();
    }

    /**
     * {@inheritDoc}
     */
    public function setAjoutContactsEleves($ajoutContactsEleves)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAjoutContactsEleves', [$ajoutContactsEleves]);

        return parent::setAjoutContactsEleves($ajoutContactsEleves);
    }

    /**
     * {@inheritDoc}
     */
    public function getAjoutContactsEleves()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAjoutContactsEleves', []);

        return parent::getAjoutContactsEleves();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeContactEleves($codeContactEleves)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeContactEleves', [$codeContactEleves]);

        return parent::setCodeContactEleves($codeContactEleves);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeContactEleves()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeContactEleves', []);

        return parent::getCodeContactEleves();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenuHtmlCourrier($contenuHtmlCourrier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenuHtmlCourrier', [$contenuHtmlCourrier]);

        return parent::setContenuHtmlCourrier($contenuHtmlCourrier);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenuHtmlCourrier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenuHtmlCourrier', []);

        return parent::getContenuHtmlCourrier();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenuHtmlMail($contenuHtmlMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenuHtmlMail', [$contenuHtmlMail]);

        return parent::setContenuHtmlMail($contenuHtmlMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenuHtmlMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenuHtmlMail', []);

        return parent::getContenuHtmlMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDispoALaDemande($dispoALaDemande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDispoALaDemande', [$dispoALaDemande]);

        return parent::setDispoALaDemande($dispoALaDemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getDispoALaDemande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDispoALaDemande', []);

        return parent::getDispoALaDemande();
    }

    /**
     * {@inheritDoc}
     */
    public function setTampon($tampon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTampon', [$tampon]);

        return parent::setTampon($tampon);
    }

    /**
     * {@inheritDoc}
     */
    public function getTampon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTampon', []);

        return parent::getTampon();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodecourriertype($codecourriertype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodecourriertype', [$codecourriertype]);

        return parent::setCodecourriertype($codecourriertype);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodecourriertype()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCodecourriertype();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodecourriertype', []);

        return parent::getCodecourriertype();
    }

}
