<?php

namespace EleveBundle\Repository\EntityIconet;

/**
 * AgentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentsRepository extends \Doctrine\ORM\EntityRepository
{
}
