<?php

namespace EleveBundle\Repository\EntityIconet;

/**
 * ProfessionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionsRepository extends \Doctrine\ORM\EntityRepository
{
}
